# ----------------------- #
# Main Configs #
# ----------------------- #

url: http://arkokoley.github.io/sani
title: My Sani Blog
subtitle: Less Code. More Blogging.
author: Your Name
simple_search: http://google.com/search
description:
sidebar:

auto: true
server: true
permalink: none
exclude:
- .gitignore
- README.md

prose:
  #rooturl: "_posts"
  metadata: 
    _posts/blog: |
      published: true
      layout: post
      title: Your Post Title
      abstract: Short summary of your post.
      author_twitter: 
      author: 
      categories:
      - articles

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
# Jekyll & Plugins #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: 
permalink: /blog/:title/
code_dir: downloads/code
category_dir: blog/categories
markdown: maruku
pygments: true # default python pygments have been replaced by pygments.rb

paginate: 10 # Posts per page on the blog index
pagination_dir: blog # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;" # "Continue reading" link text at the bottom of excerpted articles

titlecase: true # Converts page and post titles to titlecase

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
