# ----------------------- #
# Main Configs #
# ----------------------- #

url: http://yoursite.com
title: My Sani Blog
subtitle: Less Code. More Blogging.
author: Your Name
simple_search: http://google.com/search
description:
sidebar:

auto: true
server: true
permalink: none
exclude:
- .gitignore
- README.md

prose:
  #rooturl: "_posts"
  metadata: 
    _posts/blog: |
      published: true
      layout: post
      title: Your Post Title
      abstract: Short summary of your post.
      author_twitter: 
      author: 
      categories:
      - articles

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
# Jekyll & Plugins #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: 
permalink: /blog/:title/
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10 # Posts per page on the blog index
pagination_dir: blog # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;" # "Continue reading" link text at the bottom of excerpted articles

titlecase: true # Converts page and post titles to titlecase

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Twitter widget:

